services:
  identity.center.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_HTTP_PORTS=${ASPNETCORE_HTTP_PORTS}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ConnectionStrings:IRedis=identity.center.redis:6379,password=${REDIS_PASSWORD},abortConnect=false,connectTimeout=5000,syncTimeout=5000
      - BrokerOptions:Host=identity.center.broker
      - BrokerOptions:Username=${RABBITMQ_DEFAULT_USER}
      - BrokerOptions:Password=${RABBITMQ_DEFAULT_PASS}
      - BrokerOptions:VirtualHost=/
      - BrokerOptions:Exchange=comms.exchange
      - ConnectionStrings:IdentityContext=${ASPNETCORE_APPCONNECTIONSTRING}
      - WithConfigurationContext:Id=${IDENTITY_MAINAPP_ID}
    ports:
      - "56676:8080"
  identity.center.redis:
    expose:
      - 6379
    command: >
      redis-server
      --requirepass "${REDIS_PASSWORD}"
      --maxmemory 3gb
      --maxmemory-policy allkeys-lru
      --maxclients 10000
      --tcp-backlog 65536
      --tcp-keepalive 300
      --appendonly yes
      --appendfsync everysec
      --no-appendfsync-on-rewrite yes
      --lazyfree-lazy-eviction yes
      --lazyfree-lazy-expire yes
      --active-defrag-threshold-lower 10
      --active-defrag-threshold-upper 100
  identity.center.broker:
    expose:
      - 5672
      - 15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}