services:
  identity.center.api:
    container_name: identity.center.api
    image: ${DOCKER_REGISTRY-}identitycenterapi
    build:
      context: .
      dockerfile: Identity.Center.Api/Dockerfile
  identity.center.redis:
    image: redis:7.2-alpine
    container_name: identity.center.redis
    restart: unless-stopped
  identity.center.broker:
    image: rabbitmq:3.13-management
    container_name: identity.center.broker
    restart: unless-stopped
