// <auto-generated />
using System;
using Identity.Center.Persistence.Data.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Identity.Center.Persistence.Data.Core.Migrations
{
    [DbContext(typeof(IdentityContext))]
    [Migration("20260504135442_RootRole")]
    partial class RootRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Authentication.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("app_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("hash");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<bool>("Root")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("root");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("salt");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("api_keys", "auth");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Authentication.DomainCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("created_by");

                    b.Property<int>("CredentialTypeId")
                        .HasColumnType("int")
                        .HasColumnName("credential_type_id");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CredentialTypeId", "Username")
                        .IsUnique();

                    b.ToTable("domain_credentials", "auth");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Authentication.SingleCredential", b =>
                {
                    b.Property<Guid>("AppId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("app_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("hash");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_modified_by");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("salt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("username");

                    b.HasKey("AppId", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex("AppId", "Username")
                        .IsUnique();

                    b.ToTable("single_credentials", "auth");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Authorization.ApiKeyClaim", b =>
                {
                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("api_key_id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("claim_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_modified_by");

                    b.HasKey("ApiKeyId", "ClaimId");

                    b.HasIndex("ClaimId");

                    b.ToTable("api_keys_claims", "auth");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Authorization.ClaimValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("action_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_modified_by");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("GroupId");

                    b.ToTable("claims", "auth");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Authorization.RoleClaim", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("claim_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_modified_by");

                    b.HasKey("RoleId", "ClaimId");

                    b.HasIndex("ClaimId");

                    b.ToTable("roles_claims", "auth");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Authorization.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_modified_by");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("users_roles", "auth");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Builds.App", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("DomainName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("domain_name");

                    b.Property<long>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("index");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Index"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("prefix");

                    b.HasKey("Id");

                    b.HasIndex("Index")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Prefix")
                        .IsUnique();

                    b.ToTable("apps", "build");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f9c0e66-e29f-f011-81de-00505682eca9"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Servicio de gestión de identidad",
                            Index = 1L,
                            IsDeleted = false,
                            Name = "Identity",
                            Prefix = "sid"
                        },
                        new
                        {
                            Id = new Guid("2cab2232-72a0-f011-81de-00505682eca9"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Servicios de atención telefónica centralizados",
                            Index = 2L,
                            IsDeleted = false,
                            Name = "Atenea Iris",
                            Prefix = "ais"
                        },
                        new
                        {
                            Id = new Guid("befbac57-72a0-f011-81de-00505682eca9"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Servicios de atención telefónica centralizados",
                            Index = 3L,
                            IsDeleted = false,
                            Name = "Atenea Asisya",
                            Prefix = "aay"
                        },
                        new
                        {
                            Id = new Guid("085e4fa8-72a0-f011-81de-00505682eca9"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Servicios de atención telefónica para Promotec",
                            Index = 4L,
                            IsDeleted = false,
                            Name = "Atenea Promotec",
                            Prefix = "apt"
                        },
                        new
                        {
                            Id = new Guid("99d8850b-73a0-f011-81de-00505682eca9"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Servicios de control y monitoreo de telefonía",
                            Index = 5L,
                            IsDeleted = false,
                            Name = "Central Asterisk",
                            Prefix = "ast"
                        },
                        new
                        {
                            Id = new Guid("c20bfd03-77a0-f011-81de-00505682eca9"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Administrador de credenciales de la web de finanzauto",
                            Index = 6L,
                            IsDeleted = false,
                            Name = "Finanzauto Web Admin",
                            Prefix = "fzw"
                        },
                        new
                        {
                            Id = new Guid("7b2c9ab9-77a0-f011-81de-00505682eca9"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Servicios de atención telefónica para Carfiao",
                            Index = 7L,
                            IsDeleted = false,
                            Name = "Atenea Carfiao",
                            Prefix = "acf"
                        });
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Builds.AppAllowedCredential", b =>
                {
                    b.Property<Guid>("AppId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("app_id");

                    b.Property<int>("CredentialTypeId")
                        .HasColumnType("int")
                        .HasColumnName("credential_type_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_modified_by");

                    b.HasKey("AppId", "CredentialTypeId");

                    b.HasIndex("CredentialTypeId");

                    b.ToTable("apps_allowed_credentials", "build");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Builds.AppConfigurationSection", b =>
                {
                    b.Property<Guid>("AppId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("app_id");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("value");

                    b.HasKey("AppId", "Key");

                    b.ToTable("app_settings", "build");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Builds.CredentialType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Arguments")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(max)")
                        .HasDefaultValue(new byte[] { 123, 125 })
                        .HasColumnName("arguments");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("auth_method_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("credential_types", "build");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Arguments = new byte[] { 123, 125 },
                            AuthType = "user-password",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Ingreso con usuario y contraseña generado por la aplicación",
                            IsDeleted = false,
                            Name = "Usuario y contraseña"
                        },
                        new
                        {
                            Id = 2,
                            Arguments = new byte[] { 123, 34, 107, 101, 121, 34, 58, 34, 75, 100, 78, 69, 83, 74, 101, 73, 97, 100, 81, 92, 117, 48, 48, 50, 66, 85, 92, 117, 48, 48, 50, 66, 81, 53, 81, 115, 92, 117, 48, 48, 50, 66, 56, 66, 81, 61, 61, 34, 44, 34, 100, 111, 109, 97, 105, 110, 78, 97, 109, 101, 34, 58, 34, 70, 90, 67, 79, 82, 80, 34, 125 },
                            AuthType = "qd-endpoint",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Ingreso con usuario de Dominio Finanzauto",
                            IsDeleted = false,
                            Name = "Finanzauto"
                        },
                        new
                        {
                            Id = 3,
                            Arguments = new byte[] { 123, 34, 107, 101, 121, 34, 58, 34, 75, 100, 78, 69, 83, 74, 101, 73, 97, 100, 81, 92, 117, 48, 48, 50, 66, 85, 92, 117, 48, 48, 50, 66, 81, 53, 81, 115, 92, 117, 48, 48, 50, 66, 56, 66, 81, 61, 61, 34, 44, 34, 100, 111, 109, 97, 105, 110, 78, 97, 109, 101, 34, 58, 34, 81, 66, 84, 65, 34, 125 },
                            AuthType = "qd-endpoint",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Ingreso con usuario de Dominio Quantum Data",
                            IsDeleted = false,
                            Name = "Quantum Data"
                        },
                        new
                        {
                            Id = 4,
                            Arguments = new byte[] { 123, 34, 107, 101, 121, 34, 58, 34, 75, 100, 78, 69, 83, 74, 101, 73, 97, 100, 81, 92, 117, 48, 48, 50, 66, 85, 92, 117, 48, 48, 50, 66, 81, 53, 81, 115, 92, 117, 48, 48, 50, 66, 56, 66, 81, 61, 61, 34, 44, 34, 100, 111, 109, 97, 105, 110, 78, 97, 109, 101, 34, 58, 34, 80, 84, 83, 69, 71, 85, 82, 79, 83, 34, 125 },
                            AuthType = "qd-endpoint",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Ingreso con usuario de Dominio Promotec",
                            IsDeleted = false,
                            Name = "Promotec"
                        },
                        new
                        {
                            Id = 5,
                            Arguments = new byte[] { 123, 34, 107, 101, 121, 34, 58, 34, 83, 87, 74, 70, 55, 69, 92, 117, 48, 48, 50, 66, 54, 71, 114, 102, 54, 51, 67, 111, 57, 68, 106, 121, 50, 74, 119, 61, 61, 34, 44, 34, 100, 111, 109, 97, 105, 110, 78, 97, 109, 101, 34, 58, 34, 70, 90, 67, 79, 82, 80, 34, 125 },
                            AuthType = "qd-endpoint",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Ingreso con usuario de Dominio Asisya",
                            IsDeleted = false,
                            Name = "Asisya"
                        });
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Builds.HealtCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("app_id");

                    b.Property<byte[]>("Arguments")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(max)")
                        .HasDefaultValue(new byte[] { 123, 125 })
                        .HasColumnName("arguments");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<string>("HealtCheckType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("healtcheck_type");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("healtchecks", "build");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Identity.ContactInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("bit")
                        .HasColumnName("confirmed");

                    b.Property<Guid>("ContactTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("contact_type_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_modified_by");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("salt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ContactTypeId");

                    b.HasIndex("UserId", "ContactTypeId", "Value")
                        .IsUnique();

                    b.ToTable("contact_info", "id");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<bool>("ActiveDirectoryMandatory")
                        .HasColumnType("bit")
                        .HasColumnName("ad_mandatory");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("app_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("DomainName")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("domain_name");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<bool>("Root")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("root");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("DomainName")
                        .IsUnique()
                        .HasFilter("[domain_name] IS NOT NULL");

                    b.HasIndex("Name", "AppId")
                        .IsUnique();

                    b.ToTable("roles", "id");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("document_number");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("document_type");

                    b.Property<string>("FirstLastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("first_lastname");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("SecondLastName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("second_lastname");

                    b.Property<string>("SecondName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("second_name");

                    b.HasKey("Id");

                    b.HasIndex("DocumentType", "DocumentNumber")
                        .IsUnique();

                    b.ToTable("users", "id");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Security.Action", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("actions", "sec");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Security.AppAuth", b =>
                {
                    b.Property<Guid>("AppId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("app_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<TimeSpan>("ExpirationTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time")
                        .HasDefaultValue(new TimeSpan(0, 1, 0, 0, 0))
                        .HasColumnName("expiration_time");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_modified_by");

                    b.Property<TimeSpan>("RefreshTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time")
                        .HasDefaultValue(new TimeSpan(0, 1, 30, 0, 0))
                        .HasColumnName("refresh_time");

                    b.Property<byte[]>("SignatureKey")
                        .IsRequired()
                        .HasColumnType("varbinary(900)")
                        .HasColumnName("signature_key");

                    b.Property<bool>("TwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("two_factor_enabled");

                    b.HasKey("AppId");

                    b.HasIndex("SignatureKey")
                        .IsUnique();

                    b.ToTable("app_auth", "sec");

                    b.HasData(
                        new
                        {
                            AppId = new Guid("5f9c0e66-e29f-f011-81de-00505682eca9"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExpirationTime = new TimeSpan(0, 0, 0, 0, 0),
                            IsDeleted = false,
                            RefreshTime = new TimeSpan(0, 0, 0, 0, 0),
                            SignatureKey = new byte[] { 19, 161, 15, 77, 197, 84, 141, 150, 231, 18, 90, 115, 18, 1, 45, 18, 17, 246, 235, 91, 213, 252, 90, 154, 46, 179, 179, 170, 31, 83, 36, 100 },
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            AppId = new Guid("2cab2232-72a0-f011-81de-00505682eca9"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExpirationTime = new TimeSpan(0, 0, 0, 0, 0),
                            IsDeleted = false,
                            RefreshTime = new TimeSpan(0, 0, 0, 0, 0),
                            SignatureKey = new byte[] { 249, 18, 34, 98, 74, 76, 224, 211, 201, 247, 70, 92, 58, 65, 182, 217, 181, 96, 181, 61, 99, 191, 241, 233, 207, 26, 209, 91, 227, 46, 15, 122 },
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            AppId = new Guid("befbac57-72a0-f011-81de-00505682eca9"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExpirationTime = new TimeSpan(0, 0, 0, 0, 0),
                            IsDeleted = false,
                            RefreshTime = new TimeSpan(0, 0, 0, 0, 0),
                            SignatureKey = new byte[] { 100, 80, 12, 96, 214, 214, 199, 10, 172, 99, 43, 207, 43, 222, 15, 139, 167, 130, 34, 38, 139, 56, 253, 196, 138, 220, 102, 135, 182, 8, 128, 63 },
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            AppId = new Guid("085e4fa8-72a0-f011-81de-00505682eca9"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExpirationTime = new TimeSpan(0, 0, 0, 0, 0),
                            IsDeleted = false,
                            RefreshTime = new TimeSpan(0, 0, 0, 0, 0),
                            SignatureKey = new byte[] { 91, 226, 250, 169, 173, 40, 65, 160, 238, 110, 230, 102, 25, 36, 14, 179, 195, 15, 218, 62, 41, 138, 146, 88, 51, 114, 195, 34, 182, 196, 153, 99 },
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            AppId = new Guid("99d8850b-73a0-f011-81de-00505682eca9"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExpirationTime = new TimeSpan(0, 0, 0, 0, 0),
                            IsDeleted = false,
                            RefreshTime = new TimeSpan(0, 0, 0, 0, 0),
                            SignatureKey = new byte[] { 131, 181, 168, 162, 251, 106, 215, 25, 15, 146, 239, 52, 140, 147, 47, 226, 181, 88, 117, 23, 69, 214, 234, 176, 252, 159, 247, 115, 196, 206, 54, 141 },
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            AppId = new Guid("c20bfd03-77a0-f011-81de-00505682eca9"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExpirationTime = new TimeSpan(0, 0, 0, 0, 0),
                            IsDeleted = false,
                            RefreshTime = new TimeSpan(0, 0, 0, 0, 0),
                            SignatureKey = new byte[] { 225, 99, 122, 255, 85, 23, 96, 166, 23, 30, 120, 30, 179, 180, 171, 182, 255, 119, 18, 248, 132, 204, 37, 232, 186, 199, 63, 22, 46, 160, 16, 7 },
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            AppId = new Guid("7b2c9ab9-77a0-f011-81de-00505682eca9"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            ExpirationTime = new TimeSpan(0, 0, 0, 0, 0),
                            IsDeleted = false,
                            RefreshTime = new TimeSpan(0, 0, 0, 0, 0),
                            SignatureKey = new byte[] { 101, 206, 146, 19, 58, 149, 193, 222, 177, 24, 199, 139, 66, 42, 16, 125, 221, 209, 254, 155, 118, 208, 165, 154, 67, 252, 3, 229, 228, 15, 185, 62 },
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Security.ContactType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("ContactTypeKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ContactTypeKey")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("contact_types", "sec");

                    b.HasData(
                        new
                        {
                            Id = new Guid("433c5502-cf39-f111-81e9-00505682eca9"),
                            ContactTypeKey = "coorp-mail",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Correos internos (correos del workspace)",
                            IsDeleted = false,
                            Name = "Correo coorporativo"
                        },
                        new
                        {
                            Id = new Guid("cc763078-cf39-f111-81e9-00505682eca9"),
                            ContactTypeKey = "external-mail",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Correos externos a la organización",
                            IsDeleted = false,
                            Name = "Correo externo"
                        },
                        new
                        {
                            Id = new Guid("f953c4ae-cf39-f111-81e9-00505682eca9"),
                            ContactTypeKey = "cellphone",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Description = "Número de celular",
                            IsDeleted = false,
                            Name = "Teléfono Celular"
                        });
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Security.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset?>("LastModifiedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_modified_at_utc");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("groups", "sec");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Authentication.ApiKey", b =>
                {
                    b.HasOne("Identity.Center.Domain.Entities.Core.Builds.App", "App")
                        .WithMany("ApiKeys")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Authentication.DomainCredential", b =>
                {
                    b.HasOne("Identity.Center.Domain.Entities.Core.Builds.CredentialType", "CredentialType")
                        .WithMany("DomainCredentials")
                        .HasForeignKey("CredentialTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Identity.Center.Domain.Entities.Core.Identity.User", "User")
                        .WithMany("DomainCredentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CredentialType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Authentication.SingleCredential", b =>
                {
                    b.HasOne("Identity.Center.Domain.Entities.Core.Builds.App", "App")
                        .WithMany("Credentials")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Identity.Center.Domain.Entities.Core.Identity.User", "User")
                        .WithMany("SingleCredentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Authorization.ApiKeyClaim", b =>
                {
                    b.HasOne("Identity.Center.Domain.Entities.Core.Authentication.ApiKey", "ApiKey")
                        .WithMany("Claims")
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Identity.Center.Domain.Entities.Core.Authorization.ClaimValue", "Claim")
                        .WithMany("ApiKeys")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApiKey");

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Authorization.ClaimValue", b =>
                {
                    b.HasOne("Identity.Center.Domain.Entities.Core.Security.Action", "Action")
                        .WithMany("Claims")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Identity.Center.Domain.Entities.Core.Security.Group", "Group")
                        .WithMany("Claims")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Authorization.RoleClaim", b =>
                {
                    b.HasOne("Identity.Center.Domain.Entities.Core.Authorization.ClaimValue", "Claim")
                        .WithMany("Roles")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Identity.Center.Domain.Entities.Core.Identity.Role", "Role")
                        .WithMany("Claims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Authorization.UserRole", b =>
                {
                    b.HasOne("Identity.Center.Domain.Entities.Core.Identity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Identity.Center.Domain.Entities.Core.Identity.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Builds.AppAllowedCredential", b =>
                {
                    b.HasOne("Identity.Center.Domain.Entities.Core.Builds.App", "App")
                        .WithMany("AllowedCredentials")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Identity.Center.Domain.Entities.Core.Builds.CredentialType", "CredentialType")
                        .WithMany("Apps")
                        .HasForeignKey("CredentialTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("CredentialType");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Builds.AppConfigurationSection", b =>
                {
                    b.HasOne("Identity.Center.Domain.Entities.Core.Builds.App", "App")
                        .WithMany("ConfigurationSections")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Builds.HealtCheck", b =>
                {
                    b.HasOne("Identity.Center.Domain.Entities.Core.Builds.App", "App")
                        .WithMany("HealtChecks")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Identity.ContactInfo", b =>
                {
                    b.HasOne("Identity.Center.Domain.Entities.Core.Security.ContactType", "ContactType")
                        .WithMany("ContactInfo")
                        .HasForeignKey("ContactTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Identity.Center.Domain.Entities.Core.Identity.User", "User")
                        .WithMany("ContactInfo")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ContactType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Identity.Role", b =>
                {
                    b.HasOne("Identity.Center.Domain.Entities.Core.Builds.App", "App")
                        .WithMany("Roles")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Security.AppAuth", b =>
                {
                    b.HasOne("Identity.Center.Domain.Entities.Core.Builds.App", "App")
                        .WithOne("Auth")
                        .HasForeignKey("Identity.Center.Domain.Entities.Core.Security.AppAuth", "AppId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("App");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Authentication.ApiKey", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Authorization.ClaimValue", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Builds.App", b =>
                {
                    b.Navigation("AllowedCredentials");

                    b.Navigation("ApiKeys");

                    b.Navigation("Auth")
                        .IsRequired();

                    b.Navigation("ConfigurationSections");

                    b.Navigation("Credentials");

                    b.Navigation("HealtChecks");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Builds.CredentialType", b =>
                {
                    b.Navigation("Apps");

                    b.Navigation("DomainCredentials");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Identity.Role", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Identity.User", b =>
                {
                    b.Navigation("ContactInfo");

                    b.Navigation("DomainCredentials");

                    b.Navigation("Roles");

                    b.Navigation("SingleCredentials");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Security.Action", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Security.ContactType", b =>
                {
                    b.Navigation("ContactInfo");
                });

            modelBuilder.Entity("Identity.Center.Domain.Entities.Core.Security.Group", b =>
                {
                    b.Navigation("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
